### ISSUE TITLE
Addition of MobileNet V1

### ISSUE THREAD

**Issue by Aakash-kaushik** [mlpack/models#71]
Creating a issue to track the progress of Mobilenet and discuss things before we have a PR for this. 

Created: https://github.com/mlpack/mlpack/pull/3007 to add depthwise seperable convolutions.  
And we still don't have a final reference from which we are going to build mobilenet from but that's secondary for now, but i will keep looking for it. 

### Tasks.
1. [ ] Get https://github.com/mlpack/mlpack/pull/3007 merged.
2. [x] Using tensorflow reference to build MobileNet. 
3. [x] Start implemetation and create a PR for the same: #72 
4. [x] Get ReLU6 https://github.com/mlpack/mlpack/pull/3009 merged.

### References:
1. [Mobilenet V1 paper](https://arxiv.org/abs/1704.04861) 

cc: @zoq, @kartikdutt18

**Comment by Aakash-kaushik** [comment]
Hi, So the models present on the repos we talked about yesterday doesn't have the param `alpha` and `depthMultiplier` used so we will only be able to provide weights weights for a single config with a single image size accepted, as the image size given to mobilenet matters. 
and the tool i talked about [mmdnn](https://github.com/microsoft/MMdnn) that can only take static image sizes and the things are very rigid and hardcoded just because of that fact that any model weight is first converted to an IR and then to the framework.
So at this point i want to move forward with mobilenet V2 if that's okay?

**Comment by kartikdutt18** [comment]
I don't mind if we only provide weights only for one model config.

**Comment by Aakash-kaushik** [comment]
> I don't mind if we only provide weights only for one model config.

Should be doable then.

**Comment by Aakash-kaushik** [comment]
Mobilenet has all these configs available: https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md ignore the quantized ones, but on;y if we somehow manage to import weights from TensorFlow.
For now, I will start with the implementation of mobilenet and care less about how we are going to port the weights as that hinders a lot when I try to code the actual architecture.

**Comment by Aakash-kaushik** [comment]
I have also opened #72 to add mobilenet_v1
