### ISSUE TITLE
Tracker for improvements in models doc. 

### ISSUE THREAD

**Issue by Aakash-kaushik** [mlpack/models#74]
Following are some of the things i would work on:

- [ ] Trying to move the indexing on the left as side pane or something.
- [ ] Avoiding full path names, it print jenkins/docs and all of that as file path.
- [ ] take a look at fixed-width fonts.
- [ ] Maybe swap the theme for a more subtle one.

Feel free to point more things if you notice any and here is the [docs](https://models.mlpack.org/docs/) link if someone missed it.

**Comment by zoq** [comment]
Can we use the same blue as https://www.mlpack.org/docs.html?

**Comment by Aakash-kaushik** [comment]
> Seems like maybe we should keep this one open?

I have added the keep open tag, will work on it as soon as I get the time.
